// <auto-generated />
using BibliotekaMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotekaMS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230419152912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotekaMS.Models.Kategoria", b =>
                {
                    b.Property<int>("KategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriaId"));

                    b.Property<string>("EmriKategorise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriaId");

                    b.ToTable("Kategoria");
                });

            modelBuilder.Entity("BibliotekaMS.Models.KategoriaELibrit", b =>
                {
                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int");

                    b.HasKey("Isbn", "KategoriaId");

                    b.HasIndex("KategoriaId");

                    b.ToTable("KategoriaELibrit");
                });

            modelBuilder.Entity("BibliotekaMS.Models.Libri", b =>
                {
                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fotoja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pershkrimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Isbn");

                    b.ToTable("Libri");
                });

            modelBuilder.Entity("BibliotekaMS.Models.KategoriaELibrit", b =>
                {
                    b.HasOne("BibliotekaMS.Models.Libri", "Libri")
                        .WithMany("KategoriaELibrit")
                        .HasForeignKey("Isbn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliotekaMS.Models.Kategoria", "Kategoria")
                        .WithMany("KategoriaELibrit")
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");

                    b.Navigation("Libri");
                });

            modelBuilder.Entity("BibliotekaMS.Models.Kategoria", b =>
                {
                    b.Navigation("KategoriaELibrit");
                });

            modelBuilder.Entity("BibliotekaMS.Models.Libri", b =>
                {
                    b.Navigation("KategoriaELibrit");
                });
#pragma warning restore 612, 618
        }
    }
}
